version: '3.8'

services:
  ms-search-food:
    build:
      context: ./ms-search-food
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./logs:/app/logs
    networks:
      - ms-search-food-network

networks:
  ms-search-food-network:
    driver: bridge
