services:
  ms-auth-user:
    container_name: ms-auth-user
    build:
      context: ./ms-auth-user
      dockerfile: Dockerfile
    image: ms-auth-user
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge